//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnagramWPF {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Anagram2Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Anagram2Settings defaultInstance = ((Anagram2Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Anagram2Settings())));
        
        public static Anagram2Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LetterPoolMode {
            get {
                return ((int)(this["LetterPoolMode"]));
            }
            set {
                this["LetterPoolMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int LetterPoolCount {
            get {
                return ((int)(this["LetterPoolCount"]));
            }
            set {
                this["LetterPoolCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TrackUsedWords {
            get {
                return ((bool)(this["TrackUsedWords"]));
            }
            set {
                this["TrackUsedWords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int BonusTime {
            get {
                return ((int)(this["BonusTime"]));
            }
            set {
                this["BonusTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int BonusWords {
            get {
                return ((int)(this["BonusWords"]));
            }
            set {
                this["BonusWords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TimerMode {
            get {
                return ((int)(this["TimerMode"]));
            }
            set {
                this["TimerMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int SecondsPerLetter {
            get {
                return ((int)(this["SecondsPerLetter"]));
            }
            set {
                this["SecondsPerLetter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PlayTickSound {
            get {
                return ((bool)(this["PlayTickSound"]));
            }
            set {
                this["PlayTickSound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TickSoundFile {
            get {
                return ((string)(this["TickSoundFile"]));
            }
            set {
                this["TickSoundFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AwardBonusTime {
            get {
                return ((bool)(this["AwardBonusTime"]));
            }
            set {
                this["AwardBonusTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int StaticTimeValue {
            get {
                return ((int)(this["StaticTimeValue"]));
            }
            set {
                this["StaticTimeValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal BestPercent {
            get {
                return ((decimal)(this["BestPercent"]));
            }
            set {
                this["BestPercent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal WorstPercent {
            get {
                return ((decimal)(this["WorstPercent"]));
            }
            set {
                this["WorstPercent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal AveragePercent {
            get {
                return ((decimal)(this["AveragePercent"]));
            }
            set {
                this["AveragePercent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int GamesPlayed {
            get {
                return ((int)(this["GamesPlayed"]));
            }
            set {
                this["GamesPlayed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int GamesWon {
            get {
                return ((int)(this["GamesWon"]));
            }
            set {
                this["GamesWon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TotalPossibleWords {
            get {
                return ((int)(this["TotalPossibleWords"]));
            }
            set {
                this["TotalPossibleWords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TotalFoundWords {
            get {
                return ((int)(this["TotalFoundWords"]));
            }
            set {
                this["TotalFoundWords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SaveStats {
            get {
                return ((bool)(this["SaveStats"]));
            }
            set {
                this["SaveStats"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2012-11-01")]
        public global::System.DateTime StatsDate {
            get {
                return ((global::System.DateTime)(this["StatsDate"]));
            }
            set {
                this["StatsDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TotalFoundGameWord {
            get {
                return ((int)(this["TotalFoundGameWord"]));
            }
            set {
                this["TotalFoundGameWord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MostFoundWords {
            get {
                return ((int)(this["MostFoundWords"]));
            }
            set {
                this["MostFoundWords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TotalPoints {
            get {
                return ((int)(this["TotalPoints"]));
            }
            set {
                this["TotalPoints"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PoiintsPerGame {
            get {
                return ((int)(this["PoiintsPerGame"]));
            }
            set {
                this["PoiintsPerGame"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseClassNameDictionary {
            get {
                return ((bool)(this["UseClassNameDictionary"]));
            }
            set {
                this["UseClassNameDictionary"] = value;
            }
        }
    }
}
